
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_7pKMeDzn85ETfF10wTz@mysql-pollos-pollos.d.aivencloud.com:22700/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_7pKMeDzn85ETfF10wTz
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


